### PR TITLE
Update for gRPC 1.1 compatibility (breaking change)

### PR DESCRIPTION
**Pull request by crclark**
In the 1.1 release of gRPC, several headers were moved around and the `gpr_slice` type was replaced with `grpc_slice`. This PR makes `grpc-haskell` compatible with gRPC 1.1.\*, __but it breaks compatibility with gRPC 0.15-1.0__. 

I would like to use `#if` to support both, but as far as I can tell, gRPC doesn't `#define` a `GRPC_VERSION`. I could potentially hack around it with `#ifdef grpc_slice`, but I'm not sure if it would be worth it given gRPC's currently fast development pace -- newer versions should be preferred because lots of bugs are still being fixed. 

One last wrinkle: `nix-build release.nix -A grpc-haskell` now fails with

```
/tmp/nix-build-grpc-haskell-0.0.0.0.drv-0/gRPC-haskell/dist/build/libHSgrpc-haskell-0.0.0.0-8ZQha4M7OeMBAkc86RjN3Y-ghc8.0.1.so: undefined reference to `gpr_slice_unref'
```

which is very strange because 1. this version of the code no longer contains references to `gpr_slice_unref` and 2. `gpr_slice_unref` is still defined (but deprecated) in the gRPC headers that the build is using. I'm still opening this PR in the hopes that someone can spot my mistake. It *does* build and pass tests successfully without Nix, using globally-installed gRPC.

### CODE REVIEW

**Comment by intractable** [comment]
Hmm, I'm not yet able to reproduce your errors. I haven't investigated further yet, but this is the message I'm currently seeing when I try to build from your branch via `stack`:

```
grpc-haskell-0.0.0.0: build
Preprocessing library grpc-haskell-0.0.0.0...

/Users/joel/w/grpc-haskell/cbits/grpc_haskell.c:210:32: error:
     error: passing 'struct (anonymous struct at /usr/local/include/grpc/impl/codegen/grpc_types.h:421:5)' to parameter of incompatible type 'grpc_byte_buffer *' (aka 'struct grpc_byte_buffer *')
          grpc_byte_buffer_destroy(op->data.send_message);
                                   ^~~~~~~~~~~~~~~~~~~~~

/nix/store/aq3ddm22ckflfc43l1ss1s8918jnqlas-grpc-1.1.4-ed7d06a/include/grpc/byte_buffer.h:70:57: error:
     note: passing argument to parameter 'byte_buffer' here
GRPCAPI void grpc_byte_buffer_destroy(grpc_byte_buffer *byte_buffer);
                                                        ^

/Users/joel/w/grpc-haskell/cbits/grpc_haskell.c:259:25: error:
     error: assigning to 'struct (anonymous struct at /usr/local/include/grpc/impl/codegen/grpc_types.h:421:5)' from incompatible type 'grpc_byte_buffer *' (aka 'struct grpc_byte_buffer *')
      op->data.send_message = grpc_byte_buffer_copy(payload);
                            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

/Users/joel/w/grpc-haskell/cbits/grpc_haskell.c:275:34: error:
     error: assigning to 'struct (anonymous struct at /usr/local/include/grpc/impl/codegen/grpc_types.h:435:5)' from incompatible type 'grpc_metadata_array *'
      op->data.recv_initial_metadata = *arr;
                                     ^ ~~~~

/Users/joel/w/grpc-haskell/cbits/grpc_haskell.c:284:25: error:
     error: assigning to 'struct (anonymous struct at /usr/local/include/grpc/impl/codegen/grpc_types.h:441:5)' from incompatible type 'grpc_byte_buffer **' (aka 'struct grpc_byte_buffer **')
      op->data.recv_message = payload_recv;
                            ^ ~~~~~~~~~~~~
4 errors generated.
`gcc' failed in phase `C Compiler'. (Exit code: 1)
```

Do any of those errors look familiar to you? Interestingly, `nix-shell release.nix -A grpc-haskell.env` does work for me, but attempting to build with `cabal` there results in the same compilation errors as above. I just didn't want to dig any further in case there's a missing push or there's a workaround to these errors that you might already know about.

**Comment by crclark** [comment]
@intractable Ah, it looks like you're using the just-released version 1.2.0. It looks like even more changes have been made to the headers in that version. gRPC is quite the moving target... I guess the next task is updating the code to 1.2.0! I'll close this PR and reopen once I update further.

**Comment by intractable** [comment]
Okay, thanks! FWIW I am not sure it was using 1.2.0 -- I used the revs for grpc that came from `release.nix`, so it should be the same version you were trying to build with...

**Comment by crclark** [comment]
Oops! I was looking at `gpr_types.h` when the error said `grpc_types.h`. Yeah, it looks like that problem is actually in 1.1.4. At any rate, since 1.2.0 is out and apparently fixes still more bugs in the C core, I'll just update to that.

**Comment by intractable** [comment]
Okay, sounds good. Thanks @crclark!

**Pull request closed without merging**
